spring.application.name=Day_19-03-2026__Spring_Rest_and_Spring_Data_JPA

server.port=8085
spring.devtools.restart.enabled=true
spring.mvc.view.suffix=.html

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Saksham
spring.datasource.url=jdbc:mysql://localhost:3306/trainee_data
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true