spring.application.name=spring-data-app
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Saksham
spring.datasource.url=jdbc:mysql://localhost:3306/springData
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
